import mongoose from 'mongoose';

const NewsfeedSchema = new mongoose.Schema({
    user_email: {   //Foreign Key
        type: String,
        trime: true,
        required: "Sender Email is required"
    },
    content: {
        type: String,
        required: "Enter something",
        trim: true
    },
    upvotes: {
        type: Number,
        default: 0,
    },
    // comment_ids: [String],
    created: {
        type: Date,
        default: Date.now
    },
    //feed_id will be generated by mongoDB
})

export default mongoose.model('Newsfeed', NewsfeedSchema)